stages:
  - packaging
  - build_docker_image
default:
  image: maven:3.8.2-openjdk-17

variables:
     MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

run unit test and package:
  inherit:
    default: true
    variables: true
  stage: packaging
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
  cache:
    paths:
      - .m2/repository

